---
dist: xenial
language: node_js
git:
  depth: 5
node_js: stable
cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile

script:
  - yarn lint
