name: CI
on:
  - push
  - pull_request

jobs:
  Quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Installing
        run: yarn --frozen-lockfile --perfer-offline --link-duplicates

      - name: Lint
        run: yarn lint
